### ISSUE TITLE
AIhub conversion not working with strawberry dataset

### ISSUE THREAD

**Issue by ccomkhj** [ccomkhj/cvOps#3]
AIhub conversion not working with strawberry dataset because it has different format comparing to tomato dataset.

I want to have a yaml config file to handle different format of samples.

i.e.
```yaml
file_name: imagePath
height: imageHeight
width: imageWidth
...

```
